// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtDLwvvZHUCDHBzQ5GJj-BfTWYwJcp-Ow',
    appId: '1:424969022196:web:93b82e102be3e0ff4a8ca1',
    messagingSenderId: '424969022196',
    projectId: 'csc4360-hw02-chatapp',
    authDomain: 'csc4360-hw02-chatapp.firebaseapp.com',
    storageBucket: 'csc4360-hw02-chatapp.firebasestorage.app',
    measurementId: 'G-46BER67ZE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZkaWZx75deNe_M2I8A0_8Ey4zt1QnoBs',
    appId: '1:424969022196:android:71b3ef26cd694bad4a8ca1',
    messagingSenderId: '424969022196',
    projectId: 'csc4360-hw02-chatapp',
    storageBucket: 'csc4360-hw02-chatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8GvMvZvYroO4baVZrnCK6DjD4u9wZG5Q',
    appId: '1:424969022196:ios:629cd66fe912659f4a8ca1',
    messagingSenderId: '424969022196',
    projectId: 'csc4360-hw02-chatapp',
    storageBucket: 'csc4360-hw02-chatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8GvMvZvYroO4baVZrnCK6DjD4u9wZG5Q',
    appId: '1:424969022196:ios:629cd66fe912659f4a8ca1',
    messagingSenderId: '424969022196',
    projectId: 'csc4360-hw02-chatapp',
    storageBucket: 'csc4360-hw02-chatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtDLwvvZHUCDHBzQ5GJj-BfTWYwJcp-Ow',
    appId: '1:424969022196:web:880d3e3a2285d2124a8ca1',
    messagingSenderId: '424969022196',
    projectId: 'csc4360-hw02-chatapp',
    authDomain: 'csc4360-hw02-chatapp.firebaseapp.com',
    storageBucket: 'csc4360-hw02-chatapp.firebasestorage.app',
    measurementId: 'G-SCF9TF29X4',
  );
}
