// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkPkVo2yxN-UPHx47j64jwvu4AP0UC2II',
    appId: '1:76397572307:web:1d74f73223eb28151ee426',
    messagingSenderId: '76397572307',
    projectId: 'csc4360-activity16-fbauth',
    authDomain: 'csc4360-activity16-fbauth.firebaseapp.com',
    storageBucket: 'csc4360-activity16-fbauth.firebasestorage.app',
    measurementId: 'G-4QG04FTZV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXvaARqrp8pJdbNwuDSYVGMnnyZxHSkxw',
    appId: '1:76397572307:android:5752cb0e8272e71d1ee426',
    messagingSenderId: '76397572307',
    projectId: 'csc4360-activity16-fbauth',
    storageBucket: 'csc4360-activity16-fbauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsRp2gP_52_ky0XkSynmewH53Y7IUY_0',
    appId: '1:76397572307:ios:09962b29a5f630691ee426',
    messagingSenderId: '76397572307',
    projectId: 'csc4360-activity16-fbauth',
    storageBucket: 'csc4360-activity16-fbauth.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCsRp2gP_52_ky0XkSynmewH53Y7IUY_0',
    appId: '1:76397572307:ios:09962b29a5f630691ee426',
    messagingSenderId: '76397572307',
    projectId: 'csc4360-activity16-fbauth',
    storageBucket: 'csc4360-activity16-fbauth.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkPkVo2yxN-UPHx47j64jwvu4AP0UC2II',
    appId: '1:76397572307:web:08a6ab1ba631ce301ee426',
    messagingSenderId: '76397572307',
    projectId: 'csc4360-activity16-fbauth',
    authDomain: 'csc4360-activity16-fbauth.firebaseapp.com',
    storageBucket: 'csc4360-activity16-fbauth.firebasestorage.app',
    measurementId: 'G-Z8MGRE145W',
  );
}
